### PR TITLE
io.js Twitter banner

### PR DESCRIPTION
**Pull request by vjk2005**
Icons are still rough and I have some more tweaks to do before they look consistent.

### CODE REVIEW

**Comment by mikeal** [comment]
@domenic is the messaging about the ES6 stuff accurate?

**Comment by a0viedo** [comment]
really nice :clap:

**Comment by domenic** [comment]
Yeah. I might say "block scope" instead of "block scopes"

**Comment by vjk2005** [comment]
@a0viedo :+1:  : )

@domenic I’ll fix it in the next PR : )

**Comment by domenic** [comment]
Or even "block scoping"

**Comment by dotproto** [comment]
@vjk2005 Others have said it before, but still, love the work you're doing for io.js

**Comment by bnb** [comment]
@svincent @vjk2005 +1.

**Comment by vjk2005** [comment]
@svincent thank you!

**Pull request merged**
