### PR TITLE
adds sample format for local initiatives

### PR DESCRIPTION
**Pull request by homosaur**
Created a sample format for entering verified local initiatives being assigned in #251 

cc @vdeturckheim @bnb

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@homosaur could we add a column for the name of the initiative lead or his github account (if available of courses)?

**Comment by homosaur** [comment]
@vdeturckheim yeah, I think that sounds like a pretty good idea. contact, email, github as additional fields?

**Comment by vdeturckheim** [comment]
@homosaur I'm not sure about the email, at least not if we collect that on github. Some people might not want to have their address publicly disclosed.

**Comment by homosaur** [comment]
@vdeturckheim good point, let's just go github and twitter. 99% of people are going to be on one of those two things or have a contact method on their public meetup info

**Comment by vdeturckheim** [comment]
@homosaur this should be good for a first iteration

**Comment by homosaur** [comment]
@vdeturckheim I have contact point right now which could actually be anything. In my case it's a Meetup page which seems ideal. Perhaps we should just pop a README into the local_initiatives directory giving guidelines on the different info you are allowed to use for this?

**Comment by vdeturckheim** [comment]
seems alright to me
@nodejs/evangelism can we get another review here ? :)

**Comment by bnb** [comment]
Looks like a good start. One thing I do want to make sure we discuss is an actual human contact. Meetups and initiatives often become inactive - definitely want to make sure that people aren't being directed to ones that have become inactive. 

If we can actually get a human point of contact that we can talk to - that we can ask if the meetup/initiative is inactive - then we can build a simple and slim process around removing inactive ones after a certain amount of time or a review process.

A simple way to do this would be to ask for a twitter handle of an organizer. That's typically the most direct way to contact people. Not sure if we want to expose emails publicly.

**Comment by homosaur** [comment]
@bnb I think there's two ways for the info here to go out of date, either that the group becomes defunct (which we will have to edit for anyway) or that the group gets a new organizer. Probably having their Twitter or Github handle would at least make it easier to verify the data occasionally because you wouldn't have to chase someone down. Let's say then we have a link to a web address if it exists, then a link to a public profile for primary organizer. Sound good?

**Comment by vdeturckheim** [comment]
LGTM with latest commit.
@bnb what do you think ?

We can iterate later on the format as needs appear. But it is a good point to start working.

**Review by bnb — CHANGES_REQUESTED** [review]
Only comment is that, at this point, it would probably be more impactful and streamlined to have them all in one file, instead of breaking it down so far. 

Something like:

```
# Local Initiatives
## North America
Location | Event | Website | Contact Point
 +-------- | ----- | ------- | -------------
 +St. Louis | Node.jSTL | <https://www.meetup.com/node-jSTL/> | Twitter: @thekeithchester
## Europe
Location | Event | Website | Contact Point
 +-------- | ----- | ------- | -------------
 +London | Node London | <Node London Link> | Twitter: @nodelondonmaintainer

...
```

I think this structure would be easier to start off with - early on in the Evangelism WG, I broke things down a lot, and it actually made it a bit more complex for others to get started _and_ for visibility of information generally.

**Comment by bnb** [comment]
Definitely curious if anyone else has other ideas on another way to structure it with high visibility and low contribution friction! 😊

**Comment by homosaur** [comment]
@bnb LGTM, let's just start with a single document and start breaking it down as it gets too unwieldy

**Review by bnb — APPROVED** [review]
:shipit:

**Comment by vdeturckheim** [comment]
\o/ Thanks @homosaur for this PR
thanks @bnb for the merge ;)

**Pull request merged**
