### PR TITLE
Add/edit main files, move SMSG to docs folder

### PR DESCRIPTION
**Pull request by bnb**
Covers #20.

Added the main files CONTRIBUTING.md and GOVERNANCE.md to the repo.
Edited README.md to reflect the WG members, as it's supposed to.

Also moved the social media style guide to the documents folder.

### CODE REVIEW

**Comment by yosuke-furukawa** [comment]
LGTM. +1!!

**Comment by rosskukulinski** [comment]
+1 from me, but now there's a merge conflict with the gittim Readme changes.  @bnb if you can rebase, I'll merge this in.

**Comment by bnb** [comment]
There's no merge conflicts, but it seems the part where there was the error is how it was before. Sorry, I'm not super familiar with git. Tried figuring out how to rebase, but I didn't do it right.

**Comment by rosskukulinski** [comment]
No worries, thanks @bnb.  Merging.

**Pull request merged**
