### PR TITLE
Removing weekly updates from this repo (moved to new.nodejs.org)

### PR DESCRIPTION
**Pull request by mikeal**
I've ported all the old posts to work on the new blog:

https://github.com/nodejs/new.nodejs.org/commit/e72e537785d6952574c9a30d77bcbda7fdfee87d

### CODE REVIEW

**Comment by diagramatics** [comment]
Wait, should we merge this PR when the weekly updates are now set to go without the Medium counterpart? Or is new.nodejs.org live and open to the public already?

**Comment by mikeal** [comment]
This commit is unrelated to whether or not we post on Medium.

We've been posting these markdown files here for archive and translation purposes, we've never actually published these directly we've ported them by hand to Medium.

We should no longer post the markdown files here, we should post them to new.nodejs.org. There's a seperate discussion that should happen _after_ new.nodejs.org becomes nodejs.org about whether we want to _only_ post to the new blog or if we want to post to both Medium and nodejs.org.

**Comment by diagramatics** [comment]
Ah, right. In that case before the whole thing is finalized the new weekly updates after the PR should be added for deletion too.

**Comment by bnb** [comment]
+1. @diagramatics What do you mean by your second sentence?

**Comment by bnb** [comment]
Closed in lieu of https://github.com/nodejs/evangelism/pull/165

**Comment by diagramatics** [comment]
I meant like updating the PR to delete the new weekly updates added after the PR was initially made. The new PR solves it :)

**Pull request closed without merging**
