### PR TITLE
Fixed Twitter Banner. Refined ES6 feature icons.

### PR DESCRIPTION
**Pull request by vjk2005**
See the new banner in action [here](https://twitter.com/vjk2005)

### CODE REVIEW

**Comment by bnb** [comment]
Is the resolution high enough for retina devices? #30

**Comment by vjk2005** [comment]
@bnb it’s 2x Twitter’s recommended resolution of 1500 x 500 (so 3000 x 1000).

It’s a vector so resolution can be upped even further if people are still having issues.

**Comment by bnb** [comment]
Okay, I _think_ that should do it. +1 from me. Needs a couple more +1s, and we'll merge.

**Comment by vjk2005** [comment]
:+1:

**Comment by mikeal** [comment]
updated https://twitter.com/official_iojs

just realized tho, we can't say "node.js", can you change to "node." trademark :(

**Comment by vjk2005** [comment]
@mikeal just a sec, sending PR...

**Comment by vjk2005** [comment]
@mikeal it’s in.

**Comment by mikeal** [comment]
I don't know what program you're using to create these but I think it would be helpful for the translators in particular if you could also add the raw files from that program in case they need to localize the language in the header for their social media accounts.

**Comment by vjk2005** [comment]
@mikeal good point. I’m using Photoshop and just checked in the PSD.

**Comment by bnb** [comment]
+1 for source files. I think the i18n teams would love that.

**Comment by bnb** [comment]
Merged https://github.com/iojs/evangelism/pull/35.

**Comment by rosskukulinski** [comment]
awesome, thanks so much @vjk2005

**Comment by vjk2005** [comment]
@rosskukulinski :+1: : )

**Pull request merged**
