### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### iojs/evangelism now has a Chat Room on Gitter

@rosskukulinski has just created a chat room. You can visit it here: [https://gitter.im/iojs/evangelism](https://gitter.im/iojs/evangelism?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/iojs/evangelism?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by a0viedo** [comment]
@iojs/evangelism a gitter room would be nice!

**Comment by bnb** [comment]
+1 from me. Would be good to have a place to just discuss evangelism, but I don't know how used it would be by the other WG members.

**Comment by yosuke-furukawa** [comment]
+1 !!

**Comment by dotproto** [comment]
I'm in favor of giving it a shot. Could be a useful resource.

We should probably circle back in a week or so and see how we feel about this.

**Comment by rosskukulinski** [comment]
ok, lets give it a shot, and I agree with @svincent, lets regroup in 1-2 weeks and decide if we'd like to keep it.  My thoughts are:
- Should be easy for WG members to communicate in realtime
- Unlike Slack, its tied to GitHub, which is _the_ organizational space for iojs
- It has chat history without needing to setup an IRC bot
- Major Downside: communication in gitter is NOT replicated to GitHub Issues.  We should probably still use GitHub issues as our primary means of stating our individual positions on problems/ideas

**Comment by bnb** [comment]
@rosskukulinski To be fair, Slack can be tied to GitHub with an integration, and Slack has infinite chat history.

**Comment by rosskukulinski** [comment]
Oh, fair enough.  I guess what I meant is that you don't need _another_ account to use Gittim.

**Pull request merged**
