### PR TITLE
Created a proposal roadmap for the thread summary process

### PR DESCRIPTION
**Pull request by vdeturckheim**
This follows discussions in #241 regarding the writing of articles summarizing of long threads within the organisation.

### CODE REVIEW

**Comment by bnb** [comment]
Pretty comprehensive list - LGTM.

@trevnorris, @jasnell, and @nodejs/ctc: Do you two have any further feedback on what you would like to see from this?

**Comment by vdeturckheim** [comment]
@trevnorris @jasnell , would you have time for a quick review this week? :)

**Comment by jasnell** [comment]
Absolutely

**Comment by Fishrock123** [comment]
Not particularly clear, but seems like a starting point!

**Comment by trevnorris** [comment]
Cool. I was thinking something as simple as after 50 comments a summary is written for the previous 50. Also give them a special tag so my script can collapse everything down that's not a summary.

Overall this looks good.

**Comment by bnb** [comment]
Looks like we have general consensus. Merged! ❤️

**Pull request merged**
