### PR TITLE
Add Social Media Style Guide

### PR DESCRIPTION
**Pull request by bnb**
Added social media style guide that I wrote. The key points of every section are highlighted in bold. I'd love to get feedback on any points, and discuss changes with anyone interested.

### CODE REVIEW

**Comment by mikeal** [comment]
Initial feedback is +1 :)

Haven't had a chance to read it more in depth though. Would love to get @emilyrose's feedback :)

**Comment by dotproto** [comment]
I really like it, @bnb, so don't be fooled by the nitpicking I'm about to delve into.
- The last sentence in "**Don't talk trash**" feels out of place. I'd suggest something like:
  - "Instead, focus on encouraging positive, open discussion of io.js and its community."
- What you refer to as "capital case" is more commonly known as "title case".
- Regarding title case, I'm not familiar with the rule that a "title does not need to be capital case if it is a full sentence, with structure and punctuation." Was this taken from a specific style guide?
- The active vs. passive voice section isn't quite right. There are a couple "active" examples that contain phrases like "was" or "have been." 
  - "io.js (subject) was forked (action) from Node.js (object), and has been worked on heavily (secondary, compound action)." That sentence is missing an agent; _who_ did the forking?
    - Possible alternative: The io.js technical committee forked Node.js in late 2014 and the community began rallying around the project shortly thereafter.
  - "npm (subject) has been minimally changed (action) to be compatible (tricky action-like; "minimally changed" is the action that has been actively done, compatibility was a result of that action) with io.js (object) as well as Node.js (second object)."
    - Man that's a tricky sentence. Active voice is hard.

Annnd that's it.

**Comment by bnb** [comment]
@svincent Thanks for the comments! I really appreciate you taking the time to look through it. 

I've got some time on my commute tomorrow morning and evening, as well as a couple hours midday, that I will use to fix this as quickly as possible. An update to the PR will land tomorrow, and it'd be great if you could review it again, @svincent.

To be honest, the full sentence title bit is something I created while writing this. It seemed like a good idea to me, as some people tend to use whole sentences to title posts, and it seems extremely strange to put a period after a bunch of words that are capitalized, but if _anybody_ has the _slightest_ objection, I'll remove it without worry.

With regard to the active voice, thanks for pointing out the agent. I'm not familiar with every part of a sentence, every part of speech, etc. by name, so I sometimes have a hard time programmatically going through, dissecting and labeling a sentence.

**Comment by mikeal** [comment]
> The last sentence in "Don't talk trash" feels out of place. I'd suggest something like: "Instead, focus on encouraging positive, open discussion of io.js and its community."

I do think we should change the copy "Don't talk trash" but I think we do need something in there about _not_ saying negative things about people, projects, etc.

**Comment by bnb** [comment]
Updated to reflect @svincent's comments. I'm going to go through it another time and make it more localization-friendly.

**Comment by bnb** [comment]
And also another section for adding Markdown styling suggestions for consistent Markdown across all platforms and media.

**Comment by dotproto** [comment]
FYI I'll give this a read over lunch (in ~1-2 hours).

**Comment by bnb** [comment]
Attempted to make it easier for localization groups to translate, if they want to. Also changed some sentence structure + grammar stuff. I have a few more ideas that I am implementing now, but I have to do a few other things first and might not be able to finish them tonight.

Sorry I pushed this PR so far before it was ready - I wasn't aware of how much editing I'd be doing to it, and that I would continue getting ideas for it. My bad.

**Comment by dotproto** [comment]
I'm juggling some stuff as well. @bnb I'd be happy to help by hashing out some ideas or be a sounding board over IRC or Hangouts over the next couple days if you're interested. Send a [doodle](http://doodle.com) my way if you like.

**Comment by bnb** [comment]
Okay @svincent, here's my Doodle: http://doodle.com/zi7x2zwzet547u7n
Can also talk on IRC throughout the day. Pretty much any time from now until Sunday I can talk on IRC, and at those times I can do a Hangout or something.

**Comment by mikeal** [comment]
should we merge this as-is and then you both can discuss making changes to it?

**Comment by dotproto** [comment]
I'm okay with that. Iterative process and all.

**Comment by affinity-matrix** [comment]
I just now saw _the_ @mikeal's mention; apologies for such belated feedback.

Overall I think this looks great! 

I really appreciate the fact that we're thinking about these things. I'm particularly fond of the mentions of active voice and appropriate title case.

My only real concern with the content as it stands now is the lack of direction on when to just be quiet. I'm probably as enthusiastic about positivity as the next person, but I think there is value in knowing when  not to engage or respond. 

I'm not sure exactly how to frame that within the context of this document, but I thought it was worth mentioning. Other than that, it looks awesome. Great job! :+1:

**Comment by mikeal** [comment]
good point on when not to comment. i think i could probably go through the log of recent tweets and find things i didn't comment on and add those reasons to such a document.

**Comment by bnb** [comment]
@emilyrose @mikeal It'd be great to add those to this document. My vision for this was to be a complete document that posters can refer to and find everything they need to represent io.js appropriately. 

When _not_ to respond is a very important point, and something I pretty much negated with some of my writing in this. 

@emilyrose Can you give me some general points/ideas of when not to respond? @mikeal I'd be very interested in hearing your reasoning behind not commenting on specific tweets; it would help a lot.

**Comment by affinity-matrix** [comment]
@bnb sure:
- Situations where a detractor is making inflammatory remarks that have already been addressed or erroneous claims that have already been disproven.
- Posts authored by accounts that are obviously created for sock puppetry/harassment.
- Threads that are already dragging on with insufficient direction or coherent discussion.

I'm sure it could be worded better though.

**Comment by bnb** [comment]
Thanks @emilyrose! I'll work those in to the next update of this.

**Comment by mikeal** [comment]
Here’s a good example https://twitter.com/zedshaw/status/571464419521118208 https://twitter.com/zedshaw/status/571464419521118208

Nothing positive can come from engaging with this comment :)

**Pull request merged**
