### PR TITLE
Update DCO to v1.1

### PR DESCRIPTION
**Pull request by williamkapke**
See: https://github.com/nodejs/TSC/issues/92

### CODE REVIEW

**Comment by williamkapke** [comment]
@nodejs/evangelism Please review.

**Comment by Knighton910** [comment]
Instead of [paragraph] ; or

## 

can we do it more like:

[paragraph]

 or 

[paragraph]

**Comment by Knighton910** [comment]
In general LGTM

**Comment by julianduque** [comment]
LGTM

**Pull request merged**
