### PR TITLE
Create weekly-update.2015-04-10.md

### PR DESCRIPTION
**Pull request by Gioyik**
CC #53

### CODE REVIEW

**Comment by Gioyik** [comment]
Sorry for mistakes, everything is OK now.

**Comment by mikeal** [comment]
We should add:
- Continued work on a new dev policy for node.js/io.js https://github.com/jasnell/dev-policy
- Remove reference to NodeConf on the 8th and 9th, only NodeConf Adventure is happening.
- TC call from Wednesday https://www.youtube.com/watch?v=OjlK8k10oyo

**Comment by Gioyik** [comment]
changes are done

**Comment by Gioyik** [comment]
@julianduque changes are made.

**Comment by yosuke-furukawa** [comment]
LGTM. thank you for your nice work.

**Comment by yosuke-furukawa** [comment]
iojs next nightly can be downloaded [here](https://iojs.org/download/next-nightly/).

We can use `class` syntax by default. 

See also:
https://github.com/iojs/io.js/issues/1393#issuecomment-91794970

**Comment by Gioyik** [comment]
@yosuke-furukawa should we include the nightly news in this weekly meeting?

**Comment by julianduque** [comment]
@Gioyik let's make it for the next week, merging and publishing now.

**Pull request merged**
