### PR TITLE
Add weekly update 2015-09-11.md

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
@nodejs/evangelism

### CODE REVIEW

**Comment by JungMinu** [comment]
@yosuke-furukawa Thanks for your update:heart: , I will write next week update :smile:

**Comment by yosuke-furukawa** [comment]
Thank you! Please help me...

**Comment by JungMinu** [comment]
@yosuke-furukawa Next week, How can I post weekly-update to medium and nodejs.org?

**Comment by yosuke-furukawa** [comment]
@JungMinu If your weekly update will merged in this repo, I will post your weekly update to medium and nodejs.org ! 

medium entries are authorized by twitter account. if you would like to post medium directly, you need to get official-iojs twitter account. But we will stop posting medium sooner or later. if so, you don't need to get the account.

nodejs.org is managed by nodejs/new.nodejs.org, we need to send PR the repo.

**Pull request merged**
