### PR TITLE
Add JungMinu as a member of evangelism WG

### PR DESCRIPTION
**Pull request by yosuke-furukawa**
Congrats!!
We have got a new member !!
@JungMinu , I am looking forward to working with you.

### CODE REVIEW

**Comment by yosuke-furukawa** [comment]
@mikeal @bnb please add her as an evangelism WG member.

**Comment by JungMinu** [comment]
@yosuke-furukawa @mikeal @bnb Thanks in advance :)
I will do my best :smile:

**Comment by Fishrock123** [comment]
Invite sent for https://github.com/orgs/nodejs/teams/evangelism

**Comment by JungMinu** [comment]
@Fishrock123 Thanks a lot :)

**Pull request merged**
