### PR TITLE
Removing weeklies, these should be committed directly to the website now.

### PR DESCRIPTION
**Pull request by mikeal**
We've missed the last 3 weekly posts on the website. I just ported them but I think we should remove this directory from the evangelism repo to avoid this confusion in the future.

Also, weekly updates should be announced on the nodejs twitter account. When one is posted to the blog please send a Twitter Direct Message to @nodejs with the text of the tweet and it will get posted ASAP.

### CODE REVIEW

**Comment by JungMinu** [comment]
@mikeal Next time, should I make a pull request to `new.nodejs.org repo` for review?
I would love to make a pull request or commit directly to `new.nodejs.org repo` if I can be a website WG member. :smile:

**Comment by mikeal** [comment]
@JungMinu you can make a pull request without being a WG member, anyone can send a pull request to it :)

Once a contribution is accepted then we can add you to the Website WG.

**Comment by JungMinu** [comment]
@mikeal Thanks, I'd love to :)

**Comment by mikeal** [comment]
The process is nearly identical except that the folder is in a different spot and there's an info header in yaml that you copy/paste/edit. Check out https://github.com/nodejs/new.nodejs.org/pull/204

**Comment by JungMinu** [comment]
@mikeal Thanks :smiley:

**Comment by yosuke-furukawa** [comment]
In my opinion, we need reviews weekly updates from other evangelists. At least I need to get some feedback. Because I am not Native English speakers. I know your concern. we should avoid the confusion. 
But I think evangelism repo is easy to discuss and review our updates.

**Comment by mikeal** [comment]
@yosuke-furukawa good idea, but we could have the evangelism WG review in that repo if we add @nodejs/evangelism as a writer to the repo, see https://github.com/nodejs/new.nodejs.org/issues/205

**Comment by yosuke-furukawa** [comment]
@mikeal Thank you!! And I would like to discuss when we should stop publishing weekly updates in Medium.

**Comment by mikeal** [comment]
@yosuke-furukawa hrm... let me think about that.

**Comment by bnb** [comment]
Can this be closed, as of https://github.com/nodejs/evangelism/pull/131?

**Comment by bnb** [comment]
+1, any objections? If none are voiced, I'll merge in two days.

**Comment by mikeal** [comment]
Go ahead and merge it :)

**Pull request merged**
